db:
  url: "unused setting"
blacklight:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core" %>
secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "somesecretkey" %>

default_publication: "midaily"
contact_address: "bhl-digital-support@umich.edu"
permissions_address: "bhl-student-pub-contact@umich.edu"

DLXS_COLLECTION: "bhl_midaily"
DLXS_SERVICE_URL: "https://path/to/service/host"

GOOGLE_ANALYTICS_PROFILES: []

icons:
  rotate_left: "rotate_left"
  rotate_right: "rotate_right"
  zoom_in: "add"
  zoom_out: "remove"
  pan: "arrow_all"
  select: "selection"

  alert: "warning"

  file_image: "image_file"
  file_pdf: "pdf"
  file_text: "text_file"
  file_zip: "text_file"

  next: "arrow_forward"
  previous: "arrow_back"
  divider: "keyboard_arrow_right"
  back_to_top: "keyboard_arrow_up"

  close: "close"
  search: "search"

  info: "info_outline"

